### ISSUE TITLE
no --version flag to kartograph ....

### ISSUE THREAD

**Issue by a2800276** [kartograph/kartograph.org#25]
I just installed kartograph as described on the website and have a couple of issues I'd like to report. Unfrotunately, there's no way to get a dump of the environment that's installed. 

So consider the lack "--version" flag my first issue :)

Here is my setup, this applies to any further bugs:

```
$ uname -a
Darwin <host> 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012;     
root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64

$ python --version
Python 2.7.1
```

kartograph was installed as described here:

   http://kartograph.org/docs/kartograph.py/install-macosx.html

using the no-gdal.

Furthermore: the ne_50m_admin_0_countries example of the site runs extremely slow (>16s) I'm wondering wether this is expected or I did something wrong?

**Comment by gka** [comment]
1. This issue is posted in the wrong repository. Here is a better place: https://github.com/kartograph/kartograph.py/
2. At this moment I am very busy with other work, so I'm not working on Kartograph.py in the next weeks.
3. Pull requests are appreciated.
