### ISSUE TITLE
showcase/projections no longer working

### ISSUE THREAD

**Issue by rotsee** [kartograph/kartograph.org#41]
Seems like http://kartograph.org/showcase/projections/ is no longer working.

jQuery says `Uncaught TypeError: Cannot read property 'length' of undefined` (called at line 289: `$.each(kartograph.proj, function(p) { ...`

**Comment by beren1hand** [comment]
I would like to use this feature and wanted to show the demo to someone today. Still not working.

**Comment by DavidLemayian** [comment]
@rotsee @beren1hand It seems to be working for me right now. Could you try it again cause I can see @gka has made some updates recently. What browsers are you using?

**Comment by beren1hand** [comment]
It's working today. Wasn't the other day though. Tested it in Chrome
34.0.1847.131
and Safari 7.0.3 and Firefox 21.0

**Comment by DavidLemayian** [comment]
@beren1hand that's great to hear. Let's hope it works for @rotsee too. Cheers.

**Comment by rotsee** [comment]
Working for me too.  Yay!
