### ISSUE TITLE
How to host a local instance of the site

### ISSUE THREAD

**Issue by rukku** [kartograph/kartograph.org#8]
I'm currently trying to learn from the examples, specifically the Italia example. However, I don't know how to load the site, even on a local web server. I'm able to load the index.html at the topmost level but the I can only see the text. Do I have to do something before I load the folder into Apache? Sorry for the noobish question. I'm new to all this.

**Comment by gka** [comment]
This is a [Jekyll](http://jekyllrb.com/) site, so you have to [install Jekyll](https://github.com/mojombo/jekyll/wiki/Install) and then run it in the root directory. It will generate a folder "_site" which contains the fully rendered website. Make this your document root and it should look fine.

**Comment by rukku** [comment]
Got it. Thanks :+1:
