### ISSUE TITLE
Visual Map configurator is not working

### ISSUE THREAD

**Issue by rveciana** [kartograph/kartograph.org#9]
Hello, the web page
http://kartograph.org/showcase/editor
which was really useful, is not working anymore. The browser console gives me three errors.

**Comment by pbellon** [comment]
Same for me with these errors:

```
Uncaught ReferenceError: dat is not defined /showcase/editor/:359
Uncaught ReferenceError: kartograph is not defined /showcase/editor/:218
```

I can reproduce this bug on linux & windows and every web browser I have. (IE, chrome, firefox, rekonq, konqeror)

**Comment by marcmoncrief** [comment]
Hi. This page still isn't working for me. Would be really useful to have it back! Tried in Firefox, Chrome and Safari. Error log shows:
Uncaught ReferenceError: $script is not defined
